### ISSUE TITLE
run daemon on ubuntu 18.10 crash

### ISSUE THREAD

**Issue by netmebtc** [deroproject/derosuite#9]
github.com/deroproject/derosuite/storage.(*BoltTXWrapper).Rollback(0xc460c7c9c0)
        /home/git/gowork/src/github.com/deroproject/derosuite/storage/boltdb.go:165 +0x2f
github.com/deroproject/derosuite/blockchain.(*Blockchain).Load_Height_for_BL_ID(0xc420081ad0, 0x37ca2e0, 0xc460c7c9c0, 0x83b8df51b5fab5a5, 0x84cb606cf73f83c8, 0xca2736754da3b8af, 0x29b68ba1444101d, 0x243d)
        /home/git/gowork/src/github.com/deroproject/derosuite/blockchain/store.go:793 +0x1d4
github.com/deroproject/derosuite/blockchain.(*Blockchain).Get_Height(0xc420081ad0, 0x58)
        /home/git/gowork/src/github.com/deroproject/derosuite/blockchain/blockchain.go:343 +0x1db
github.com/deroproject/derosuite/p2p.fill_common(0xc471123328)
        /home/git/gowork/src/github.com/deroproject/derosuite/p2p/connection_handler.go:50 +0x3f
github.com/deroproject/derosuite/p2p.(*Connection).Send_TimedSync(0xc46499a480, 0x0)
        /home/git/gowork/src/github.com/deroproject/derosuite/p2p/timedsync.go:36 +0x56
github.com/deroproject/derosuite/p2p.(*Connection).Handle_TimedSync(0xc46499a480, 0xc43507f680, 0x5f, 0x5f)
        /home/git/gowork/src/github.com/deroproject/derosuite/p2p/timedsync.go:65 +0x193
github.com/deroproject/derosuite/p2p.Handle_Connection(0x37ca700, 0xc45785ca80, 0xc43d8d5ef0, 0xc420000001)
        /home/git/gowork/src/github.com/deroproject/derosuite/p2p/connection_handler.go:404 +0x6e9
created by github.com/deroproject/derosuite/p2p.P2P_Server_v2
        /home/git/gowork/src/github.com/deroproject/derosuite/p2p/controller.go:383 +0x623

goroutine 198 [semacquire]:
sync.runtime_SemacquireMutex(0xc42e18a194, 0xc4303d4a00)
        /home/git/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc42e18a190)
        /home/git/local/go/src/sync/mutex.go:134 +0x108
github.com/deroproject/derosuite/vendor/github.com/coreos/bbolt.(*DB).removeTx(0xc42e18a000, 0xc4589b3180)
        /home/git/gowork/src/github.com/deroproject/derosuite/vendor/github.com/coreos/bbolt/db.go:624 +0x52
github.com/deroproject/derosuite/vendor/github.com/coreos/bbolt.(*Tx).close(0xc4589b3180)
        /home/git/gowork/src/github.com/deroproject/derosuite/vendor/github.com/coreos/bbolt/tx.go:295 +0x37c
github.com/deroproject/derosuite/vendor/github.com/coreos/bbolt.(*Tx).rollback(0xc4589b3180)
        /home/git/gowork/src/github.com/deroproject/derosuite/vendor/github.com/coreos/bbolt/tx.go:269 +0x43
github.com/deroproject/derosuite/vendor/github.com/coreos/bbolt.(*Tx).Rollback(0xc4589b3180, 0x0, 0xc4303d4b18)
        /home/git/gowork/src/github.com/deroproject/derosuite/vendor/github.com/coreos/bbolt/tx.go:257 +0x72
github.com/deroproject/derosuite/storage.(*BoltTXWrapper).Rollback(0xc460c7c970)
        /home/git/gowork/src/github.com/deroproject/derosuite/storage/boltdb.go:165 +0x2f
github.com/deroproject/derosuite/blockchain.(*Blockchain).Load_Height_for_BL_ID(0xc420081ad0, 0x37ca2e0, 0xc460c7c970, 0x83b8df51b5fab5a5, 0x84cb606cf73f83c8, 0xca2736754da3b8af, 0x29b68ba1444101d, 0x243d)
        /home/git/gowork/src/github.com/deroproject/derosuite/blockchain/store.go:793 +0x1d4
github.com/deroproject/derosuite/blockchain.(*Blockchain).Get_Height(0xc420081ad0, 0x58)
        /home/git/gowork/src/github.com/deroproject/derosuite/blockchain/blockchain.go:343 +0x1db
github.com/deroproject/derosuite/p2p.fill_common(0xc471123148)
        /home/git/gowork/src/github.com/deroproject/derosuite/p2p/connection_handler.go:50 +0x3f
github.com/deroproject/derosuite/p2p.(*Connection).Send_TimedSync(0xc46499a480, 0x1)
        /home/git/gowork/src/github.com/deroproject/derosuite/p2p/timedsync.go:36 +0x56
github.com/deroproject/derosuite/p2p.Handle_Connection.func3(0xc46499a480, 0x37ca700, 0xc45785ca80)
        /home/git/gowork/src/github.com/deroproject/derosuite/p2p/connection_handler.go:311 +0x472
created by github.com/deroproject/derosuite/p2p.Handle_Connection
        /home/git/gowork/src/github.com/deroproject/derosuite/p2p/connection_handler.go:280 +0x4ce

goroutine 199 [chan receive]:
github.com/deroproject/derosuite/vendor/github.com/paulbellamy/ratecounter.(*RateCounter).run.func1(0xc469dbd780)
        /home/git/gowork/src/github.com/deroproject/derosuite/vendor/github.com/paulbellamy/ratecounter/ratecounter.go:51 +0x8d
created by github.com/deroproject/derosuite/vendor/github.com/paulbellamy/ratecounter.(*RateCounter).run
        /home/git/gowork/src/github.com/deroproject/derosuite/vendor/github.com/paulbellamy/ratecounter/ratecounter.go:48 +0x52

goroutine 200 [chan receive]:
github.com/deroproject/derosuite/vendor/github.com/paulbellamy/ratecounter.(*RateCounter).run.func1(0xc464762800)
        /home/git/gowork/src/github.com/deroproject/derosuite/vendor/github.com/paulbellamy/ratecounter/ratecounter.go:51 +0x8d
created by github.com/deroproject/derosuite/vendor/github.com/paulbellamy/ratecounter.(*RateCounter).run
        /home/git/gowork/src/github.com/deroproject/derosuite/vendor/github.com/paulbellamy/ratecounter/ratecounter.go:48 +0x52

goroutine 201 [chan receive]:
github.com/deroproject/derosuite/vendor/github.com/paulbellamy/ratecounter.(*RateCounter).run.func1(0xc469dbd7c0)
        /home/git/gowork/src/github.com/deroproject/derosuite/vendor/github.com/paulbellamy/ratecounter/ratecounter.go:51 +0x8d
created by github.com/deroproject/derosuite/vendor/github.com/paulbellamy/ratecounter.(*RateCounter).run
        /home/git/gowork/src/github.com/deroproject/derosuite/vendor/github.com/paulbellamy/ratecounter/ratecounter.go:48 +0x52

**Comment by netmebtc** [comment]
have solved it .  daemon need ge 2G ram , After set swap memory ,it is normal
